<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Employee_Pnum</name>
   <tag></tag>
   <elementGuidId>32e63f3b-fc40-47d8-bd06-0757fa47a3ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Employee_Pnum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Employee_Pnum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;+97612345678&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab2c741b-1711-4c4a-ab70-269da408e930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Employee_Pnum</value>
      <webElementGuid>c185ab88-6a72-48fe-81f9-0d4092af9710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3398a7e3-7514-4a39-a0e5-5671577466b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+97612345678</value>
      <webElementGuid>8ff2dd4f-e594-4f9d-9852-58c64faf1c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input ps-10 placeholder:text-white-dark</value>
      <webElementGuid>1897bcf8-5bcf-4197-8858-fdcd49ea1f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Employee_Pnum&quot;)</value>
      <webElementGuid>77455f88-e75f-4ca5-9978-60f40a82bd2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Employee_Pnum']</value>
      <webElementGuid>b8469a76-5bc2-4ba3-9408-745801d6ac3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div/div/div/form/div/div/input</value>
      <webElementGuid>cd0597f5-0c67-4882-82b5-f18900e29111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>97138cef-70ee-489e-9ef4-f37cb530de7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Employee_Pnum' and @type = 'text' and @placeholder = '+97612345678']</value>
      <webElementGuid>4ad0871e-bb0d-4db7-9f3d-279000dc4828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
