name: CI
on:
    push:
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Katalon Studio Github Action
              uses: katalon-studio/katalon-studio-github-action@v4
              with:
                  version: '9.6.0'
                  projectPath: '${{ github.workspace }}'
                  args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/New Test Suited" -apiKey= ${{ secrets.d8796f5c-950b-457d-b989-6b1648105238 }} --config -webui.autoUpdateDrivers=true'
