name: CI
on:
    push:
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: List root directory contents
              run: dir D:\a

            - name: List Thesis directory contents
              run: dir D:\a\Thesis

            - name: List project directory contents
              run: dir D:\a\Thesis\Thesis

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: '1.8'

            - name: Katalon Studio Github Action
              uses: katalon-studio/katalon-studio-github-action@v2
              with:
                  version: '9.6.0'
                  projectPath: ${{ github.workspace }}
                  args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuitePath="Test Suites/New Test Suited" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
