name: Hello world workflow
on: push
jobs:
  first-job:
    runs-on: windows-latest
      steps:
          - name: hello world
          run: echo "Hello world"
          shell: bash

          goodbye: 
          runs-on: windows- latest
          steps: 
          - name: goodbye world
          run: echo "Goodbye world"
          shell: bash
